### ISSUE TITLE
SCRFD tflite infer error: INT64 != INT32

### ISSUE THREAD

**Issue by asonee** [PINTO0309/PINTO_model_zoo#138]
Tanks for your great work!!!
when I test SCRFD tflite model which  get from https://hub.fastgit.org/PINTO0309/PINTO_model_zoo/blob/main/129_SCRFD/download.sh ,  it occurs error, the details is as follows:

#### 5 source code for simple inference testing code
```python
import numpy as np
from tensorflow.lite.python.interpreter import Interpreter
from pprint import pprint

MODEL='scrfd_500m'
H=240
W=320
input_data = np.ones((1,H,W,3), dtype=np.float32)

# tflite ==========================================================
interpreter = Interpreter(model_path='./model_float32.tflite', num_threads=4)
interpreter.allocate_tensors()
input_blob = interpreter.get_input_details()
output_blob = interpreter.get_output_details()
interpreter.set_tensor(input_blob[0]['index'], input_data)
interpreter.invoke()
output_float32 = interpreter.get_tensor(output_blob[0]['index'])
print(f'tflite sum output(float32): {np.sum(output_float32)}')
```
When I run this code,  it occurs: 
Traceback (most recent call last):
  File "infer_tflite.py", line 15, in <module>
    interpreter.allocate_tensors()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py", line 423, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/reduce.cc:223 op_context.axis->type != kTfLiteInt32 (INT64 != INT32)Node number 57 (MEAN) failed to prepare.

**Comment by PINTO0309** [comment]
Yes. I am aware that that error occurs. As per the comment you posted yesterday, you need to do the conversion again using the latest tools. SCRFD has too many different models, so the priority for reconversion is low for now.

```
$ docker pull pinto0309/openvino2tensorflow:latest
$ docker run -it --rm \
  -v `pwd`:/home/user/workdir \
  pinto0309/openvino2tensorflow:latest

or

$ pip3 install openvino2tensorflow --upgrade
```

The tool has been fixed in v1.19.3. The current latest version is v1.20.5.
https://github.com/PINTO0309/openvino2tensorflow/releases/tag/v1.19.3
![Screenshot 2021-09-14 15:05:48](https://user-images.githubusercontent.com/33194443/133203774-45a2584f-f9ad-4b8d-9998-ecf53572629a.png)

**Comment by asonee** [comment]
thanks for you replay, when I use the pinto0309/openvino2tensorflow:latest to do SCRRFD model convert,   the onnx output result is same with openvio， but  the tensorflow and tensorflow lite model output result is different with onnx output result . Would you please give me a help? 


the onnx model url: https://drive.google.com/file/d/1qPlqyvX0eZxy0o9tiR6s49zS9nyu7D6G/view?usp=sharing

the convert script:
```
INTEL_OPENVINO_DIR=/opt/intel/openvino_2021
H=480
W=640
MODEL=scrfd_500m
$INTEL_OPENVINO_DIR/deployment_tools/model_optimizer/mo.py \
--input_model onnx/${MODEL}_shape${H}x${W}.onnx \
--data_type FP32 \
--output_dir openvino/${MODEL}/${H}x${W}/FP32

openvino2tensorflow \
--model_path openvino/${MODEL}/${H}x${W}/FP32/${MODEL}_shape${H}x${W}.xml \
--model_output_path saved_model_${MODEL}_${H}x${W} \
--output_saved_model \
--output_pb \
--output_no_quant_float32_tflite \
--output_weight_quant_tflite \
--output_float16_quant_tflite \
--output_tfjs
```

the model test script:

```
import numpy as np
import onnxruntime
from tensorflow.lite.python.interpreter import Interpreter

onnx_model_path = 'onnx/scrfd_500m_shape480x640.onnx'
tflite_model_path = './saved_model_scrfd_500m_480x640/model_float32.tflite'
H = 480
W = 640
input_data_nhwc = np.ones((1, H, W, 3), dtype=np.float32)
input_data_nchw = input_data_nhwc.transpose(0, 3, 1, 2)

# onnx ==========================================================
session = onnxruntime.InferenceSession(onnx_model_path, None)

input_name = session.get_inputs()[0].name
output_names = []
for o in session.get_outputs():
    output_names.append(o.name)

results = session.run(output_names, {input_name: input_data_nchw})
output_float32 = results[0]

print(f'shape: {output_float32.shape}')
print(f'onnx sum output(float32): {np.sum(output_float32)}')


# tflite ==========================================================
interpreter = Interpreter(model_path=tflite_model_path, num_threads=4)
interpreter.allocate_tensors()
input_blob = interpreter.get_input_details()
output_blob = interpreter.get_output_details()
interpreter.set_tensor(input_blob[0]['index'], input_data_nhwc)
interpreter.invoke()
output_float32 = interpreter.get_tensor(output_blob[0]['index'])

print(f'shape: {output_float32.shape}')
print(f'tflite sum output(float32): {np.sum(output_float32)}')
```
the model test script output result is:

```
shape: (9600, 1)
onnx sum output(float32): 60.87834167480469
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
shape: (600, 1)
tflite sum output(float32): 41.069068908691406
```

**Comment by PINTO0309** [comment]
The conversion tool will do its best to automatically convert NCHW to NHWC as much as possible, but it is not mechanically able to predict the conversion shape perfectly.

The figure below is the attached image to compare the final layer.

Left: ONNX, Right: tflite
![Screenshot 2021-09-14 17:14:33](https://user-images.githubusercontent.com/33194443/133222698-a3d271d3-d65a-44b3-8715-20e07ca7c6d6.png)

The problem with this model is that the final **`Transpose`** and **`Reshape`** processes do not convert the model to the expected transposition order and shape. For example, look at the leftmost branch. The state of the internal tensor when the shape is changed from **`[15, 20, 1, 2]`** to **`[600, 1]`** should be clearly different from the state of the internal tensor when the shape is changed from **`[1, 15, 20, 2]`** to **`[600, 1]`**.

If you have such transposition or shape change mismatch problems, you can use the following functions to force the conversion tool to change its behavior.
- **6-7. Replace weights or constant values in Const OP, and add Transpose or Reshape or Cast just before/after the operation specified by layer_id**
https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op-and-add-transpose-or-reshape-or-cast-just-beforeafter-the-operation-specified-by-layer_id

The following is what is possible with this function.
1. Force **`Transpose`** insertion
2. Force **`Reshape`** insertion
3. Force insertion of **`Cast`** operations
4. Force change of transposition order for **`Transpose`** operations
5. Force shape change for **`Reshape`** operations
6. Swapping the weights of all types of operations

It is only an example, so you will need to create your own JSON for SCRFD. In the case of the sample JSON below,
1. Force transpose parameters to be in the order [0,1,2].
2. Force insertion of **`Reshape`** operation just before layer number 660 operation.
3. Forcibly insert a **`Cast`** operation immediately after the operation of layer number 680.
```json
{
    "format_version": 2,
    "layers": [
        {
            "layer_id": "659",
            "type": "Const",
            "replace_mode": "direct",
            "values": [
                0,
                1,
                2
            ]
        },
        {
            "layer_id": "660",
            "type": "Reshape",
            "replace_mode": "insert_after",
            "values": [
                2100,
                85
            ]
        },
        {
            "layer_id": "680",
            "type": "Cast",
            "replace_mode": "insert_after",
            "values": "i64"
        }
    ]
}
```

A very important point is that it is not only near the final layer where conversion problems can occur. The structure of the final converted tflite and the ONNX or OpenVINO .xml should be compared to make sure there are no problems. The mismatch in the final output values is mainly due to incorrect conversion between **`Transpose`** and **`Reshape`**. However, there are still cases where this is due to a bug in the tool, so we will fix it as needed.

**Comment by asonee** [comment]
Thank you help!
 When I convert SCRFD float32 model to int8 quant tflite model, it occurs problem 'INT8 != INT32', the details is as follows:
'''
Graph: [/data/local/tmp/sjw/tflite/2f1fa53e-1561-11ec-9cfc-0242ac110009model_integer_quant.tflite]
Enable op profiling: [1]
Loaded model /data/local/tmp/sjw/tflite/2f1fa53e-1561-11ec-9cfc-0242ac110009model_integer_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
ERROR: tensorflow/lite/kernels/depthwise_conv.cc:144 bias->type != kTfLiteInt32 (INT8 != INT32)
ERROR: Node number 56 (DEPTHWISE_CONV_2D) failed to prepare.
'''
the onnx model url: https://drive.google.com/file/d/1qPlqyvX0eZxy0o9tiR6s49zS9nyu7D6G/view?usp=sharing。

convert scripts is:
''''
INTEL_OPENVINO_DIR=/opt/intel/openvino_2021
H=480
W=640
MODEL=scrfd_500m
$INTEL_OPENVINO_DIR/deployment_tools/model_optimizer/mo.py \
--input_model ../onnx/${MODEL}_shape${H}x${W}.onnx \
--data_type FP32 \
--output_dir openvino/${MODEL}/${H}x${W}/FP32

openvino2tensorflow \
--model_path openvino/${MODEL}/${H}x${W}/FP32/${MODEL}_shape${H}x${W}.xml \
--model_output_path saved_model_${MODEL}_${H}x${W} \
--output_saved_model \
--output_pb \
--output_no_quant_float32_tflite \
--output_weight_quant_tflite \
--output_integer_quant_type 'uint8' \
--output_integer_quant_tflite
''''

the inference test script:
'''
import numpy as np
from tensorflow.lite.python.interpreter import Interpreter

MODEL='scrfd_500m'
H=480
W=640
input_data = np.ones((1,H,W,3), dtype=np.int8)

# tflite ==========================================================
interpreter = Interpreter(model_path='./saved_model_scrfd_500m_480x640/model_integer_quant.tflite', num_threads=4)
interpreter.allocate_tensors()
input_blob = interpreter.get_input_details()
output_blob = interpreter.get_output_details()
interpreter.set_tensor(input_blob[0]['index'], input_data)
interpreter.invoke()
output_int8 = interpreter.get_tensor(output_blob[0]['index'])
print(f'tflite sum output(int8): {np.sum(output_int8)}')
'''

**Comment by PINTO0309** [comment]
Please share the .xml, .bin and json as it will take time to convert.

**Comment by asonee** [comment]
openvino scrfd  .xml, .bin and json:
https://drive.google.com/file/d/1F7gYVR2rh4AiGnx8QZNr9TyyUtnpPs_O/view?usp=sharing

**Comment by PINTO0309** [comment]
There seems to be a bug in the model optimizer of TensorFlow v2.6.0. When I specified **`--use_experimental_new_quantizer`** as the workaround for the conversion option, the conversion was successful.
```
openvino2tensorflow \
--model_path ${MODEL}_shape${H}x${W}.xml \
--model_output_path saved_model_${MODEL}_${H}x${W} \
--output_saved_model \
--output_pb \
--output_no_quant_float32_tflite \
--string_formulas_for_normalization 'data / 255' \
--output_integer_quant_type 'uint8' \
--output_integer_quant_tflite \
--use_experimental_new_quantizer
```

```python
import numpy as np
from tensorflow.lite.python.interpreter import Interpreter

MODEL='scrfd_500m'
H=480
W=640
input_data = np.ones((1,H,W,3), dtype=np.float32)

# tflite ==========================================================
interpreter = Interpreter(
    model_path='saved_model_scrfd_500m_480x640/model_integer_quant.tflite',
    num_threads=4
)
interpreter.allocate_tensors()
input_blob = interpreter.get_input_details()
output_blob = interpreter.get_output_details()
interpreter.set_tensor(input_blob[0]['index'], input_data)
interpreter.invoke()
output_int8 = interpreter.get_tensor(output_blob[0]['index'])
print(f'tflite sum output(int8): {np.sum(output_int8)}')
```
```
$ python3 test.py 
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
tflite sum output(int8): 42.984375
```

**Comment by PINTO0309** [comment]
Changed **`--use_experimental_new_quantizer`** to be enabled by default.
https://github.com/PINTO0309/openvino2tensorflow/commit/25b3af27495a7431281cd5c4071d87d68651f846
https://github.com/PINTO0309/openvino2tensorflow/releases/tag/v1.20.6

**Comment by asonee** [comment]
You are so warm-hearted, Thanks a lot!
When I run this int8 quant model in DSP, There is another problem：
```
hexagon/ops/src/op_reducing_mean.c:268:Output tensor is of size 1200, but expected output tensor of size 16
hexagon/src/execute.c:167:execute() failed on node id=278 err=-1
```
I am debugging this issue, Would you please give me a favor or some advices to solve it?

**Comment by PINTO0309** [comment]
I've never used Hexagon Delegate, so I'm not familiar with the bugs on the Delegate side. However, I can tell you this: the structure of the model is correct.
![Screenshot 2021-09-15 13:04:38](https://user-images.githubusercontent.com/33194443/133368877-093b7161-250d-42a2-83e2-817fdaed9c49.png)

**Comment by asonee** [comment]
I am all gratitude！
How to implement  "transpose(0,2,1) -> reduce_mean(axis=1) -> transpose(0,2,1)" ?  I am not familiar with openvino，Would you please share the code?

**Comment by PINTO0309** [comment]
OpenVINO is not involved, we just need to add Transpose.
```python
if across_channels:
    mean = tf.math.reduce_mean(data, axis=tf.constant([-1], dtype=tf.int32), keepdims=True)
    var = tf.math.reduce_variance(data, axis=tf.constant([-1], dtype=tf.int32), keepdims=True)
else:
    if axes==2:
        tmp = tf.transpose(data, perm=[0,2,1])
        mean = tf.math.reduce_mean(tmp, axis=tf.cast(1, dtype=tf.int32), keepdims=True)
        var = tf.math.reduce_variance(tmp, axis=tf.cast(1, dtype=tf.int32), keepdims=True)
        mean = tf.transpose(mean, perm=[0,2,1])
        var = tf.transpose(var, perm=[0,2,1])
    else:
        mean = tf.math.reduce_mean(data, axis=tf.cast(axes, dtype=tf.int32), keepdims=True)
        var = tf.math.reduce_variance(data, axis=tf.cast(axes, dtype=tf.int32), keepdims=True)
```

**Comment by PINTO0309** [comment]
https://github.com/XiaoMi/nnlib/blob/master/hexagon/ops/src/op_reducing_mean.c

**Comment by PINTO0309** [comment]
https://github.com/XiaoMi/nnlib/blob/df7ad3c1b235ecfeafa6ac9448be462e3f51ec6a/hexagon/ops/src/op_reducing_mean.c#L249-L269

**Comment by PINTO0309** [comment]
https://source.codeaurora.org/quic/hexagon_nn/nnlib

**Comment by PINTO0309** [comment]
The first error has been resolved and will be closed as no progress has been made.
