### ISSUE TITLE
167_LSTR

### ISSUE THREAD

**Issue by Hank880223** [PINTO0309/PINTO_model_zoo#171]
### Issue Type

Support

### OS

Other

### OS architecture

aarch64

### Programming Language

C++

### Framework

TensorFlowLite

### Description

When I use the float32 model on Tensorflow Lite NNAPI, some ops will not support it. 
When using the float16 model, it can work normally.
Is there a way to solve the situation that these ops do not support?

log
![Screenshot from 2022-01-06 21-01-45](https://user-images.githubusercontent.com/84907438/148386972-30ef197b-468f-4608-861d-9c264f5f9622.png)

**Comment by PINTO0309** [comment]
I am not familiar with the NNAPI because I have never used it. Therefore, I do not know where the problem is because the information presented is localized. I don't even know what the image in the log you attached is supposed to mean.

What is clear is that the structure of the Float32 tflite and Float16 tflite models is exactly the same.

**Comment by Hank880223** [comment]
I put float32 tflite and float16 tflite into netron and found that float32 tflite has SPLITV operation, but float16 tflite does not. Because NNAPI does not support SPLITV, is there a way to change SPLITV to SPLIT?
Thanks !

**Comment by PINTO0309** [comment]
There are so many SPLITs that it is hard to identify the corresponding part. Can you please show me an image?

**Comment by Hank880223** [comment]
Sorry, I have seen other models. 
What is the conversion of different tensorflow versions. Is there a different version for each operation?

**Comment by Hank880223** [comment]
Sorry, I have seen other models. 
What is the conversion of different tensorflow versions. Is there a different version for each operation?
The tensorflow version executed by the program I use is 2.6.0

**Comment by PINTO0309** [comment]
>Sorry, I have seen other models.

In the end, I couldn't figure out what the problem was. Please explain properly.

>What is the conversion of different tensorflow versions. Is there a different version for each operation?

What makes the difference between versions of TensorFlow is the number of supported operation types. **`SplitV`** and **`Split`** have been supported since early versions around v2.0.0.
https://github.com/tensorflow/tensorflow/tree/v2.0.0/tensorflow/lite/kernels

There is little difference in the behavior of operators between versions of TensorFlow Lite.
