### ISSUE TITLE
Mask-RCNN unresolved custom op

### ISSUE THREAD

**Issue by SharifElfouly** [PINTO0309/PINTO_model_zoo#2]
Hey, great project!

I tried to run the Mask-RCNN tflite model and I get the following error:

`RuntimeError: Encountered unresolved custom op: NonMaxSuppressionV5.Node number 109 (NonMaxSuppressionV5) failed to prepare.`

Do you have any plans to create this operation for tflite?

**Comment by PINTO0309** [comment]
I have no plans because I do not have the skills to implement in C++. By the way, did you try the following projects? Tensorflow Lite can infer the OP that is not supported by offloading to Tensorflow. I'm working on converting other models, so I haven't tested Mask RCNN yet.
**https://github.com/PINTO0309/TensorflowLite-flexdelegate.git**

**Comment by SharifElfouly** [comment]
Wow thats awesome...
Thank you very much for the link!

**Comment by PINTO0309** [comment]
@SharifElfouly 
I was able to successfully convert without a custom OP with Tensorflow v2.2.0-rc3 (Tensorflow Lite). If you feel like it, give it a try.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/08_mask_rcnn_inceptionv2**
