### ISSUE TITLE
Question about generating onnx model [HITNet, Tiny-HITNet]

### ISSUE THREAD

**Issue by ssseeex** [PINTO0309/PINTO_model_zoo#259]
### Issue Type

Others

### OS

Ubuntu

### OS architecture

x86_64, aarch64

### Programming Language

Python

### Framework

PyTorch, ONNX

### Model name and Weights/Checkpoints URL

[hitnet](https://github.com/zjjMaiMai/TinyHITNet.git)

### Description

Hello, Thank you for you sharing this greate work. I am working on converting pytorch/tensorflow/paddle model to onnx and then to tensorrt for deployment, and when I convert the [hitnet](https://github.com/zjjMaiMai/TinyHITNet.git) I met the unsupported op problem. From the repo it can tell the model has been convert sucessfullly, but I doen't know how to go further. Hope  you can help me and how can I convert the pytorch/tensorflow model to onnx sucessfully.

Thank you!

**Comment by PINTO0309** [comment]
The issue function is a valuable resource for other engineers with similar problems.

Therefore, we can ask the following questions
1. what conversion procedures were performed
2. what error messages were displayed
3. various other information

Please provide as much of the above information as possible. It is only after that that I will suggest an appropriate solution to you.

**Comment by ssseeex** [comment]
Sorry about the missing information.
I have exported the onnx model using torch.export_onnx， and when I convert the onnx file to tensorrt it throws the exception

[TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[05/22/2022-22:09:57] [TRT] [W] onnx2trt_utils.cpp:392: One or more weights outside the range of INT32 was clamped
[05/22/2022-22:09:57] [TRT] [E] [shuffleNode.cpp::symbolicExecute::387] Error Code 4: Internal Error (Reshape_52: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])
ERROR: Failed to parse the ONNX file.
In node 63 (parseGraph): INVALID_NODE: Invalid Node - Pad_63
[shuffleNode.cpp::symbolicExecute::387] Error Code 4: Internal Error (Reshape_52: IShuffleLayer applied to shape tensor must have 0 or 1 reshape dimensions: dimensions were [-1,2])

It seems that there's that's not supported by tenosrrt, did you do any optimization for the conversion?

**Comment by PINTO0309** [comment]
The error message gave me a general idea of what to do. However, if you can zip the onnx file that is causing the problem and attach it or provide the URL of the cloud storage for download here, I can give you a more accurate answer.

**Comment by ssseeex** [comment]
Thank you for your quick reply. I have uploaded the onnx file in this link [tiny-hitnet onnx file](https://drive.google.com/file/d/15fd8mfxjCGFij0Cy3p4HMG_MtN10Ipdp/view?usp=sharing)

**Comment by PINTO0309** [comment]
The error message says that here should not be "-1".
![image](https://user-images.githubusercontent.com/33194443/169754336-c6342920-c123-4524-9301-1f2c206d101d.png)

Below is a sample script that rewrites the shape of `Reshape`. I don't think `[100,2]` is the correct shape, but I am specifying a meaningless shape to show you a sample.
https://github.com/PINTO0309/simple-onnx-processing-tools

```
docker run -it --rm \
-v `pwd`:/home/user/workdir \
ghcr.io/pinto0309/openvino2tensorflow:latest

sam4onnx \
--op_name Reshape_52 \
--input_onnx_file_path HITNet_SF.onnx \
--output_onnx_file_path HITNet_SF_shape_changed.onnx \
--input_constants 226 int64 [100,2]
```
![image](https://user-images.githubusercontent.com/33194443/169754997-eae2f7d5-8c9c-4e76-851f-a3ac9cc12fc9.png)

However, the ONNX file you provided appears to contain a large number of rather useless OPs. Thus, you could use the same steps above to gradually eliminate the problems with ONNX, but perhaps with a little more difficulty. First, I think you need to review your structure so that errors do not occur when optimizing your model with `onnx-simplifier`. 

```bash
onnxsim HITNet_SF.onnx HITNet_SF.onnx 
Simplifying...
Traceback (most recent call last):
  File "/usr/local/bin/onnxsim", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py", line 659, in main
    model_opt, check_ok = simplify(
  File "/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py", line 587, in simplify
    model = fixed_point(model, constant_folding, infer_shapes_and_optimize)
  File "/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py", line 474, in fixed_point
    x = func_a(x)
  File "/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py", line 577, in constant_folding
    res = forward_for_node_outputs(model,
  File "/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py", line 303, in forward_for_node_outputs
    res = forward(model,
  File "/usr/local/lib/python3.8/dist-packages/onnxsim/onnx_simplifier.py", line 259, in forward
    sess = rt.InferenceSession(model.SerializeToString(
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 372, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Concat_126) Op (Concat) [ShapeInferenceError] All inputs to Concat must have same rank. Input 1 has rank 1 != 2
```
If I were analyzing the structure of an ONNX file, I would try to calmly break the model down into smaller parts and perform optimization on each part.

- "A very simple tool for situations where optimization with onnx-simplifier would exceed the Protocol Buffers upper file size limit of 2GB, or simply to separate onnx files to any size you want."
  https://github.com/PINTO0309/sne4onnx

After partial optimization of the model is complete, the model can be recombined.

- Simple tool to combine(merge) onnx models
  https://github.com/PINTO0309/snc4onnx

Finally, I have created an article on how I usually optimize my models in my procedures, which you may find useful.
https://github.com/PINTO0309/20220228_intel_deeplearning_day_hitnet_demo
![153523403-afd059d7-6c5b-496e-a418-4b432e2e0f58](https://user-images.githubusercontent.com/33194443/169756527-26a729b1-5be3-45af-aaa7-86d63a4bac17.gif)

**Comment by ssseeex** [comment]
Thanks, I will try your suggestion. Just curious did  you meet the same error when you optimizing the tiny-hitnet? Did you use the procee pytorch->onnx->tensorrt for optimization?

**Comment by PINTO0309** [comment]
>did you meet the same error when you optimizing the tiny-hitnet?

No, the problem did not occur. I always apply various optimizations at the point of exporting from PyTorch to ONNX.

>Did you use the procee pytorch->onnx->tensorrt for optimization?

Yes. PyTorch->ONNX->onnx-simplifier->ONNX modifications->TensorRT

**Comment by ssseeex** [comment]
Does it need to train the network separately for different input resolution? Because from the testing I have done, the network's accuracy decreases dramatically when the input changs from high resolution to low resolution.
