### ISSUE TITLE
FAN TensorFlowLite

### ISSUE THREAD

**Issue by DonkeySmall** [PINTO0309/PINTO_model_zoo#328]
### Issue Type

Support

### OS

Windows

### OS architecture

x86_64

### Programming Language

C++

### Framework

TensorFlowLite

### Model name and Weights/Checkpoints URL

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/303_FAN

### Description

Hello, can you please add FAN TensorFlowLite demo?

**Comment by PINTO0309** [comment]
Because of the time cost, I do not actively create demo code unless a model is of great interest to me or seems practical after creating a demo. This repository welcomes pull requests for demo code.

Below is the code from which the quotes are taken.

https://github.com/PINTO0309/PINTO_model_zoo/blob/main/303_FAN/url.txt

https://github.com/hhj1897/face_alignment
https://github.com/hhj1897/fan_training
https://github.com/hhj1897/face_pose_augmentation

**Comment by DonkeySmall** [comment]
After converting original 2dfan2_alt.pth model to onnx  i get this output

![screen](https://user-images.githubusercontent.com/66531939/222915230-6e6555c2-b314-45d0-b58e-be461beb4b12.jpg)

How to get landmarks points from outputs?
