### ISSUE TITLE
About contribution of the TFLite model of DETR-like models

### ISSUE THREAD

**Issue by On-JungWoan** [PINTO0309/PINTO_model_zoo#339]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

PyTorch

### Model name and Weights/Checkpoints URL

_

### Description

Hi Pinto0309! Do you remember me? I have received a lot of help from you regarding the conversion of a DETR-like model to TFLite. In this process, I have to modify many of the structures of the models, which takes a lot of time. Therefore, I want to share my TFLite model here for people who want to use TFLite format of DETR(DN-DETR, Deformable DETR). Can you tell me how I can contribute to this repository?

**Comment by PINTO0309** [comment]
I welcome it.

It would be very helpful if you could share the following
1. URL of the repository from which the citation was taken
2. the model file you converted
3. Script used for conversion

The storage for the models is to Wasabi Storage (low cost, fast), which I have a personal contract with, so that everyone can download them at their leisure. Thus, after I commit the URL for downloading the model to this repository, there may be a way for you to contribute by having a pull request for the README, etc.

**Comment by PINTO0309** [comment]
A sample of the parts I will commit on your behalf. I intend to post an acknowledgement of the model provided by you.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/374_LaneSOD

A sample of the parts you commit to contribute.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/374_LaneSOD/demo

**Comment by On-JungWoan** [comment]
I understand it. Thank you for your response. I will organize the data, and then I will provide it to you soon(maybe in June).
Thank you for your hard work!
