### ISSUE TITLE
Script to convert RAFT models

### ISSUE THREAD

**Issue by phuelsdunk** [PINTO0309/PINTO_model_zoo#387]
### Issue Type

Documentation Feature Request

### OS

Other

### OS architecture

Other

### Programming Language

Other

### Framework

PyTorch

### Model name and Weights/Checkpoints URL

[252_RAFT](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/252_RAFT)

### Description

Hello again :)

I have been trying to reproduce your ONNX files myself, however, I do get different results:

When I export my model with `torch.onnx.export` I have to use opset version 16 and this adds `GridSample` operations in the ONNX graph. However, in your ONNX files there are no such operations included and I see that they have been replaced by `GatherElements`.

So my question is, how can I create models similar to yours?

**Comment by PINTO0309** [comment]
https://zenn.dev/pinto0309/scraps/2766a953754dea

**Comment by phuelsdunk** [comment]
I have observed that your models are much faster than my own converted ones. Did you do any model optimization?

**Comment by PINTO0309** [comment]
All of my generated models committed to this zoo have been specially optimized. All five years. Thus, for RAFT, the special optimization work required to run on the old runtime environment, which is more than two years old, was necessary. Essentially, we believe that as of 2024, the system will run at high speed without special optimization work.

However, I am not really interested in optimizing an architecture that is several years old, since RAFT is designed to be quite operationally heavy in the architecture itself.
