### ISSUE TITLE
Documentation on using 403_trt_pose_hand on non trt systems?

### ISSUE THREAD

**Issue by avatarrokuaskingquestions** [PINTO0309/PINTO_model_zoo#417]
### Issue Type

Documentation Feature Request

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

trt_pose_hand, https://github.com/PINTO0309/PINTO_model_zoo/tree/main/403_trt_pose_hand

### Description

Can run the trt_hand_pose models on any Ubuntu system but functions required to parse the information are all in the C++ layer of trt_pose (such as [find_peaks](https://github.com/search?q=repo%3ANVIDIA-AI-IOT%2Ftrt_pose+find_peaks+language%3APython&type=code&l=Python)). Have you heard of anyone reimplementing this code and if they'd be willing for you to link to it? Or if the functions are actually just basic enough that they're made in other libraries a pointer would help people to use the models in other setups.

**Comment by PINTO0309** [comment]
I have little interest in NVIDIA's implementation, as I find processing at keypoints to be an unrealistic idea for real world use.

I think their implementation is hardly an implementation of DeepLearning because it is a very inefficient implementation that uses a lot of symbolic loops.

You might want to ask ChatGPT or something.

**Comment by avatarrokuaskingquestions** [comment]
Thanks for the quick response! Will keep that in mind...
