### ISSUE TITLE
Request for TF or TFJS models for CenterFace and RetinaFace

### ISSUE THREAD

**Issue by vladmandic** [PINTO0309/PINTO_model_zoo#80]
#### 8. Version of ONNX: **1.8.1**

This is a request to provide CenterFace and/or RetinaFace models.

`CenterFace` reference implementation is at <https://github.com/Star-Clouds/CenterFace>  
I've tried converting included `ONNX` model to `TF` using `onnx-tf`, but converted model has input shape [10,3,32,32]   
Depth ordering is non-standard (3), but that's ok  
But input it should be image with any width&height divisible by 32, not fixed [10,32,32]  

`RetinaFace` refrerence implementation is at <https://github.com/deepinsight/insightface/tree/master/detection/RetinaFace>  
But published model is `MXNet` which I have no experience with at all

**Comment by PINTO0309** [comment]
First, I converted CenterNet and committed it.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/095_centerface**

**Comment by PINTO0309** [comment]
In addition to the 1-batch version, a 10-batch version of the model has been generated and committed.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/095_centerface**

**Comment by PINTO0309** [comment]
RetinaFace has been converted and committed. Since you didn't explicitly state what you wanted, I generated it with a resolution of 512x512. You can change the resolution yourself if you want. saved_model, pb, tfjs, tf-trt, coreml, onnx, quantized tflite, OpenVINO IR, Myriad Inference Blob.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/main/096_RetinaFace**
![Screenshot 2021-03-06 13:20:07](https://user-images.githubusercontent.com/33194443/110194949-b43fef00-7e7e-11eb-9a3e-76ad40ce3f4a.png)

**Comment by PINTO0309** [comment]
If it is as expected, close the issue.

**Comment by vladmandic** [comment]
thank you!
